//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _123321123321111111111
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassMenu
    {
        public int ID { get; set; }
        public int ClassId { get; set; }
        public int IdDishMenu { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual DishMealTime DishMealTime { get; set; }
    }
}
